print("Please inser the following")
print()
adjective = input("adjetive: ")
animal = input("animal: ")
verb1 = input("verb: ")
exclamation = input("exclamation: ")
verb2 = input ("verb: ")
verb3 = input("verb: ")
print()
print()
print("Your story is: ")
print()
print(f"The other day, I was really in trouble. It all started when I saw a very\n{adjective} {animal} {verb1} down the hallway. '{exclamation}!' I yelled. but all\nI could think to do was to {verb2} over and over. Miraculously, \nthat caused it to stop, but not before it tried to {verb3}\nright in front of my family.")