print("Hello"),print("My name is Marcobot")
name = input("what is your name? ")
print("Nice to meet you"),print(name)
color = input("What is your favorite color? ")
print("Your favorite color is"),print(color)
print("That is a beatifull color"), print("Thank you so much")