# ask for information with variables.
print("Plese enter the following information")
First_Name = input("Insert your first name ")
Last_Name = input("Insert your last name ")
Email_Address = input("Insert your Email Address ")
Phone_Number = input("Inser your Phone Number ")
Job_Title = input("Inser your Job Title ")
ID_Number = input("Insert your ID Number ")
print()
print("The ID Number is:")
print()
#print the Information like a ID badge
print()
print("------------------------------")
print()
print(f"{Last_Name.upper()}, {First_Name}")
print(f"{Job_Title.capitalize()}")
print(f"ID {ID_Number}")
print()
print()
print(f"{Email_Address.lower()}")
print(f"{Phone_Number}")
print("------------------------------")